include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/_deployment.yml'

stages:
  - deploy

.deploy:
  variables:
    STACK: confluent
    DD_AWS_REGION: ${AWS_REGION}

.deploy-development:
  environment:
    name: dev/${SERVICE_NAME}

.deploy-production:
  environment:
    name: pro/${SERVICE_NAME}

.deploy-kf-1:
  variables: &deploy-kf-1-variables
    SERVICE_NAME: kf-1

.deploy-kf-2:
  variables: &deploy-kf-2-variables
    SERVICE_NAME: kf-2

.deploy-kf-3:
  variables: &deploy-kf-3-variables
    SERVICE_NAME: kf-3

.deploy-kf-1-development:
  extends: .deploy-development
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-1.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-1.dev.yml
    <<: *deploy-kf-1-variables

.deploy-kf-2-development:
  extends: .deploy-development
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-2.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-2.dev.yml
    <<: *deploy-kf-2-variables

.deploy-kf-3-development:
  extends: .deploy-development
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-3.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-3.dev.yml
    <<: *deploy-kf-3-variables

.deploy-kf-1-production:
  extends: .deploy-production
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-1.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-1.prod.yml
    <<: *deploy-kf-1-variables

.deploy-kf-2-production:
  extends: .deploy-production
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-2.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-2.prod.yml
    <<: *deploy-kf-2-variables

.deploy-kf-3-production:
  extends: .deploy-production
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-3.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-3.prod.yml
    <<: *deploy-kf-3-variables

.deploy-support-branch: &deploy-support-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_COMMIT_BRANCH == "master" ||
          $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_COMMIT_BRANCH
      when: manual
      allow_failure: true

deploy-kf-1-support-branch-development:
  extends: .deploy-kf-1-development
  <<: *deploy-support-branch

deploy-kf-2-support-branch-development:
  extends: .deploy-kf-2-development
  <<: *deploy-support-branch

deploy-kf-3-support-branch-development:
  extends: .deploy-kf-3-development
  <<: *deploy-support-branch

.deploy-stable-branch: &deploy-stable-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "master" ||
          $CI_COMMIT_BRANCH == "main"
      when: manual
      allow_failure: true

deploy-kf-1-stable-branch-development:
  extends: .deploy-kf-1-development
  <<: *deploy-stable-branch

deploy-kf-2-stable-branch-development:
  extends: .deploy-kf-2-development
  <<: *deploy-stable-branch

deploy-kf-3-stable-branch-development:
  extends: .deploy-kf-3-development
  <<: *deploy-stable-branch

deploy-kf-1-stable-branch-production:
  extends: .deploy-kf-1-production
  <<: *deploy-stable-branch

deploy-kf-2-stable-branch-production:
  extends: .deploy-kf-2-production
  <<: *deploy-stable-branch

deploy-kf-3-stable-branch-production:
  extends: .deploy-kf-3-production
  <<: *deploy-stable-branch

.deploy-tag: &deploy-tag
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true

deploy-kf-1-tag-development:
  extends: .deploy-kf-1-development
  <<: *deploy-tag

deploy-kf-2-tag-development:
  extends: .deploy-kf-2-development
  <<: *deploy-tag

deploy-kf-3-tag-development:
  extends: .deploy-kf-3-development
  <<: *deploy-tag

deploy-kf-1-tag-production:
  extends: .deploy-kf-1-production
  <<: *deploy-tag

deploy-kf-2-tag-production:
  extends: .deploy-kf-2-production
  <<: *deploy-tag

deploy-kf-3-tag-production:
  extends: .deploy-kf-3-production
  <<: *deploy-tag
