version: '3.5'

services:
  kafka-3:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    hostname: kf-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk-1:${ZK_PORT},zk-2:${ZK_PORT},zk-3:${ZK_PORT}
      KAFKA_JMX_HOSTNAME: kf-3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:${KF_PORT}
      KAFKA_LISTENERS: PLAINTEXT://:${KF_PORT}
      KAFKA_OPTS: -javaagent:${JMX_PROMETHEUS_JAVAAGENT_PATH}=${JMX_HTTP_PORT}:${JMX_PROMETHEUS_CONFIG_PATH}
      KAFKA_LOG_DIRS:
      KAFKA_LOG_CLEANER_ENABLE:
      KAFKA_LOG_CLEANUP_POLICY:
      KAFKA_LOG_CLEANER_MIN_CLEANABLE_RATIO:
      KAFKA_LOG_CLEANER_MIN_COMPACTION_LAG_MS:
      KAFKA_LOG_ROLL_HOURS:
      KAFKA_NUM_PARTITIONS:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:
      KAFKA_DEFAULT_REPLICATION_FACTOR:
      KAFKA_MIN_INSYNC_REPLICAS:
      KAFKA_OFFSETS_RETENTION_MINUTES:
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES:
      KAFKA_MESSAGE_MAX_BYTES:
      KAFKA_JMX_PORT:
      KAFKA_LOG4J_ROOT_LOGLEVEL:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
      KAFKA_INTER_BROKER_LISTENER_NAME:
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE:
    networks:
      kafka-net:
        aliases:
          - kf-3
      metric-net:
    configs:
      - source: jmx-prometheus-javaagent
        target: ${JMX_PROMETHEUS_JAVAAGENT_PATH}
      - source: jmx-prometheus-config
        target: ${JMX_PROMETHEUS_CONFIG_PATH}
    volumes:
      - kf-data-vol:/var/lib/kafka/data
      - kf-secrets-vol:/etc/kafka/secrets
    healthcheck:
      test: wget -q -O /dev/null -t 1 http://localhost:${JMX_HTTP_PORT}
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-2m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-5m}

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

volumes:
  kf-secrets-vol:
    name: ${KF_3_SECRETS_VOL_NAME}

configs:
  jmx-prometheus-javaagent:
    name: ${JMX_PROMETHEUS_JAVA_AGENT_NAME}
    external: true

  jmx-prometheus-config:
    name: ${JMX_PROMETHEUS_CONFIG_NAME}
    external: true
