version: '3.5'

services:
  kafka-2:
    environment:
      KAFKA_HEAP_OPTS: -Xmx1g -Xms1g
    deploy:
      placement:
        constraints:
          - node.hostname == ${KF_2_PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-2G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.2}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-1639M}

volumes:
  kf-data-vol:
    name: ${KF_2_DATA_VOL_NAME}
