version: '3.5'

services:
  kafka-3:
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:${KF_PORT},EXT://${PUBLIC_HOSTNAME}:3${KF_PORT}
      - KAFKA_LISTENERS=PLAINTEXT://:${KF_PORT},EXT://0.0.0.0:${KF_PORT_EXT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_HEAP_OPTS=-Xmx1g -Xms1g
    ports:
      - target: ${KF_PORT_EXT}
        published: 3${KF_PORT}
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 1639M

volumes:
  kf-data-vol:
    name: ${KF_DATA_VOL_NAME:-kf-3-data-vol}
