version: '3.5'

services:
  kafka-3:
    environment:
      KAFKA_HEAP_OPTS: -Xmx2g -Xms2g
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}c
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-3G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.2}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-2458M}

volumes:
  kf-data-vol:
    name: ${KF_3_DATA_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: ${KF_DATA_VOL_SIZE}
      ebstype: ${KF_DATA_VOL_EBS_TYPE}
